spring:
  datasource:
    url: jdbc:mysql://60.205.3.93:3306/api?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 12252MySQL@Remilia
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80

mybatis:
  mapper-locations: classpath*:mapper/*.xml